init offset = -2

init python:
    gui.init(1280, 720)

define gui.hover_sound = "audio/gui/sfx/hover.mp3"
define gui.activate_sound = "audio/gui/sfx/select.mp3"
define gui.accent_color = '#ffffff'
define gui.idle_color = '#413d3d'
define gui.idle_small_color = '#333'
define gui.hover_color = '#5f5f5f'
define gui.selected_color = '#2b1c23'
define gui.insensitive_color = '#aaaaaa7f'
define gui.muted_color = '#6666a3'
define gui.hover_muted_color = '#9999c1'
define gui.text_color = '#ffffff'
define gui.interface_text_color = '#ffffff'
define gui.default_font = "gui/font/MotivaSans.otf"
define gui.name_font = "gui/font/MotivaSans.otf"
define gui.interface_font = "gui/font/MotivaSans.otf"
define gui.text_size = 22
define gui.name_text_size = 24
define gui.interface_text_size = 24
define gui.label_text_size = 28
define gui.notify_text_size = 16
define gui.title_text_size = 38
define gui.textbox_height = 182
define gui.textbox_yalign = 0.99
define gui.name_xpos = 350
define gui.name_ypos = -3
define gui.name_xalign = 0.5
define gui.namebox_width = 168
define gui.namebox_height = 39
define gui.namebox_borders = Borders(5, 5, 5, 2)
define gui.namebox_tile = False
define gui.text_xpos = 268
define gui.text_ypos = 62
define gui.text_width = 744
define gui.text_xalign = 0.0
define gui.button_width = None
define gui.button_height = 36
define gui.button_borders = Borders(4, 4, 4, 4)
define gui.button_tile = False
define gui.button_text_font = gui.interface_font
define gui.button_text_size = gui.interface_text_size
define gui.button_text_idle_color = gui.idle_color
define gui.button_text_hover_color = gui.hover_color
define gui.button_text_selected_color = gui.selected_color
define gui.button_text_insensitive_color = gui.insensitive_color
define gui.button_text_xalign = 0.0
define gui.radio_button_borders = Borders(28, 4, 4, 4)
define gui.check_button_borders = Borders(28, 4, 4, 4)
define gui.confirm_button_text_xalign = 0.5
define gui.page_button_borders = Borders(10, 4, 10, 4)
define gui.quick_button_text_font = "gui/font/Feather.ttf"
define gui.quick_button_text_size = 25
define gui.quick_button_text_idle_color = "#fff"
define gui.quick_button_text_hover_color = "#f00"
define gui.quick_button_text_selected_color = "#777"
define gui.quick_button_text_insensitive_color = "#444"
define gui.choice_button_width = 420
define gui.choice_button_height = None
define gui.choice_button_tile = False
define gui.choice_button_borders = Borders(100, 5, 100, 5)
define gui.choice_button_text_font = gui.default_font
define gui.choice_button_text_size = gui.text_size
define gui.choice_button_text_xalign = 0.5
define gui.choice_button_text_idle_color = "#000"
define gui.choice_button_text_hover_color = "#ffccff"
define gui.slot_button_width = 276
define gui.slot_button_height = 206
define gui.slot_button_borders = Borders(10, 10, 10, 10)
define gui.slot_button_text_size = 14
define gui.slot_button_text_xalign = 0.5
define gui.slot_button_text_idle_color = gui.idle_small_color
define gui.slot_button_text_hover_color = gui.hover_color
define config.thumbnail_width = 256
define config.thumbnail_height = 144
define gui.file_slot_cols = 3
define gui.file_slot_rows = 2
define gui.navigation_xpos = 80
define gui.skip_ypos = 10
define gui.notify_ypos = 45
define gui.choice_spacing = 22
define gui.navigation_spacing = 6
define gui.pref_spacing = 10
define gui.pref_button_spacing = 0
define gui.page_spacing = 0
define gui.slot_spacing = 10
define gui.frame_borders = Borders(4, 4, 4, 4)
define gui.confirm_frame_borders = Borders(40, 40, 40, 40)
define gui.skip_frame_borders = Borders(16, 5, 50, 5)
define gui.notify_frame_borders = Borders(16, 5, 40, 5)
define gui.frame_tile = False
define gui.bar_size = 36
define gui.scrollbar_size = 12
define gui.slider_size = 30
define gui.bar_tile = False
define gui.scrollbar_tile = False
define gui.slider_tile = False
define gui.bar_borders = Borders(4, 4, 4, 4)
define gui.scrollbar_borders = Borders(4, 4, 4, 4)
define gui.slider_borders = Borders(4, 4, 4, 4)
define gui.vbar_borders = Borders(4, 4, 4, 4)
define gui.vscrollbar_borders = Borders(4, 4, 4, 4)
define gui.vslider_borders = Borders(4, 4, 4, 4)
define gui.unscrollable = "hide"
define config.history_length = 50
define gui.history_height = None
define gui.history_name_xpos = 150
define gui.history_name_ypos = 0
define gui.history_name_width = 150
define gui.history_name_xalign = 1.0
define gui.history_text_xpos = 170
define gui.history_text_ypos = 5
define gui.history_text_width = 740
define gui.history_text_xalign = 0.0
define gui.nvl_borders = Borders(0, 10, 0, 20)
define gui.nvl_height = 115
define gui.nvl_spacing = 10
define gui.nvl_name_xpos = 430
define gui.nvl_name_ypos = 0
define gui.nvl_name_width = 150
define gui.nvl_name_xalign = 1.0
define gui.nvl_text_xpos = 450
define gui.nvl_text_ypos = 8
define gui.nvl_text_width = 590
define gui.nvl_text_xalign = 0.0
define gui.nvl_thought_xpos = 240
define gui.nvl_thought_ypos = 0
define gui.nvl_thought_width = 780
define gui.nvl_thought_xalign = 0.0
define gui.nvl_button_xpos = 450
define gui.nvl_button_xalign = 0.0
